#pragma once

enum ERenderPipelineStageID
{
    RENDER_PIPELINE_STAGE_SHADOW_MAP,
    RENDER_PIPELINE_STAGE_FORWARD,
    RENDER_PIPELINE_STAGE_COMPUTE_SKINNING,
    RENDER_PIPELINE_STAGE_COMPUTE_PARTICLES,

    RENDER_PIPELINE_STAGE_MAX
};

class RenderPipelineStage
{
};