include(FetchContent)

function(fetch_package name)
    message(STATUS "Searching for ${name}")

    set(options REQUIRED)
    set(oneValueArgs TAG LOCAL REQUIRE)
    set(multiValueArgs DIST GIT)
    cmake_parse_arguments(FETCH "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(TARGET ${FETCH_REQUIRE})
        return()
    endif()

    if(FETCH_LOCAL)
        message(STATUS "Searching for local ${FETCH_LOCAL}")
        find_package(${FETCH_LOCAL} CONFIG QUIET)
        if(${FETCH_LOCAL}_FOUND)
            if(TARGET ${FETCH_REQUIRE})
                message(STATUS "Found ${FETCH_LOCAL}")
                return()
            endif()
        endif()
    endif()

    set(CURRENT_PLATFORM "")
    if(WIN32)
        set(CURRENT_PLATFORM "WIN32")
    elseif(APPLE)
        set(CURRENT_PLATFORM "MACOS")
    elseif(UNIX)
        set(CURRENT_PLATFORM "UNIX")
    endif()

    if(FETCH_DIST)
        list(LENGTH FETCH_DIST dist_len)

        foreach(idx RANGE 0 ${dist_len} 1)
            list(GET FETCH_DIST ${idx} dist_platform)
            math(EXPR next_idx "${idx} + 1")
            if(next_idx LESS dist_len)
                list(GET FETCH_DIST ${next_idx} dist_url)
                if(dist_platform STREQUAL CURRENT_PLATFORM OR dist_platform STREQUAL "DEFAULT")
                    message(STATUS "Downloading ${name} binary for ${CURRENT_PLATFORM} from ${dist_url}")
                    
                    set(dist_dir "${CMAKE_BINARY_DIR}/_deps/${name}_dist")
                    set(dist_archive "${dist_dir}/archive.tar.gz")

                    file(DOWNLOAD "${dist_url}" "${dist_archive}" STATUS download_status)
                    list(GET download_status 0 status_code)
                    if(NOT status_code EQUAL 0)
                        message(WARNING "Failed downloading ${name} from ${dist_url}. Trying next source...")
                        continue()
                    endif()

                    file(MAKE_DIRECTORY "${dist_dir}")
                    execute_process(COMMAND ${CMAKE_COMMAND} -E tar xzf "${dist_archive}" WORKING_DIRECTORY "${dist_dir}")

                    find_package(${name} CONFIG REQUIRED PATHS "${dist_dir}" NO_DEFAULT_PATH)
                    if(${name}_FOUND)
                        if(TARGET ${FETCH_REQUIRE})
                            message(STATUS "Found binary distribution of ${name} for ${CURRENT_PLATFORM}")
                            return()
                        endif()
                    else()
                        message(WARNING "Binary distribution for ${CURRENT_PLATFORM} did not contain CMake config")
                    endif()

                    break()
                endif()
            endif()
        endforeach()
    endif()

    if(FETCH_GIT)
        foreach(git_url ${FETCH_GIT})
            set(fetch_name "${name}_git")
            FetchContent_Declare(${fetch_name}
                GIT_REPOSITORY ${git_url}
                GIT_TAG ${FETCH_TAG}
            )
            FetchContent_MakeAvailable(${fetch_name})
            if(FETCH_REQUIRE)
                if(TARGET ${FETCH_REQUIRE})
                    message(STATUS "Fetched ${name} using Git")
                    return()
                endif()
            endif()
        endforeach()
    endif()

    if(FETCH_REQUIRE)
        if(NOT TARGET ${FETCH_REQUIRE})
            message(FATAL_ERROR "Could not obtain package ${name}.")
        endif()
    else()
        message(WARNING "Could not obtain package ${name}.")
    endif()
endfunction()